apiVersion: v1
kind: ConfigMap
metadata:
  name: keneyapp-config
data:
  APP_NAME: "KeneyApp"
  APP_VERSION: "1.0.0"
  API_V1_PREFIX: "/api/v1"
  DEBUG: "False"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ALLOWED_ORIGINS: "https://keneyapp.example.com"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
