apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - redis-deployment.yaml
  - postgres-deployment.yaml
  - ingress.yaml
  - configmap.yaml
  - secret.yaml
commonLabels:
  app.kubernetes.io/part-of: keneyapp
